version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: main
    open-pull-requests-limit: 10
    labels:
      - 'Dependencies'
      - 'JS'
    schedule:
      interval: daily
